name: Percy Visual Tests

on:
  push:
    branches: [ main, master ]
  pull_request_target:
    branches: [ main, master ]
    types: [opened, synchronize]

jobs:
  percy-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Storybook
      run: npm run test
      
    - name: Run Percy visual tests
      run: npx percy storybook ./storybook-static
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}