name: Percy Visual Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  percy-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Percy tests
      run: npm run test
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      continue-on-error: true
        
    - name: Check Percy build status
      run: |
        if [ -n "$PERCY_TOKEN" ]; then
          echo "Percy token available - build should be created"
        else
          echo "Warning: Percy token not available on this PR"
          exit 1
        fi
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}